export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const FETCH_ERROR_INGREDIENTS = "FETCH_ERROR_INGREDIENTS";